using System;
using System.Collections.Generic;

#nullable disable

namespace Dummy_BC_Diagnos_MVC_2.Models
{
    public partial class CronusAustraliaPtyLtdSalesHeader437dbf0e84ff417a965dEd2bb9650972
    {
        public byte[] Timestamp { get; set; }
        public int DocumentType { get; set; }
        public string No { get; set; }
        public string SellToCustomerNo { get; set; }
        public string BillToCustomerNo { get; set; }
        public string BillToName { get; set; }
        public string BillToName2 { get; set; }
        public string BillToAddress { get; set; }
        public string BillToAddress2 { get; set; }
        public string BillToCity { get; set; }
        public string BillToContact { get; set; }
        public string YourReference { get; set; }
        public string ShipToCode { get; set; }
        public string ShipToName { get; set; }
        public string ShipToName2 { get; set; }
        public string ShipToAddress { get; set; }
        public string ShipToAddress2 { get; set; }
        public string ShipToCity { get; set; }
        public string ShipToContact { get; set; }
        public DateTime OrderDate { get; set; }
        public DateTime PostingDate { get; set; }
        public DateTime ShipmentDate { get; set; }
        public string PostingDescription { get; set; }
        public string PaymentTermsCode { get; set; }
        public DateTime DueDate { get; set; }
        public decimal PaymentDiscount { get; set; }
        public DateTime PmtDiscountDate { get; set; }
        public string ShipmentMethodCode { get; set; }
        public string LocationCode { get; set; }
        public string ShortcutDimension1Code { get; set; }
        public string ShortcutDimension2Code { get; set; }
        public string CustomerPostingGroup { get; set; }
        public string CurrencyCode { get; set; }
        public decimal CurrencyFactor { get; set; }
        public string CustomerPriceGroup { get; set; }
        public byte PricesIncludingVat { get; set; }
        public string InvoiceDiscCode { get; set; }
        public string CustomerDiscGroup { get; set; }
        public string LanguageCode { get; set; }
        public string SalespersonCode { get; set; }
        public string OrderClass { get; set; }
        public int NoPrinted { get; set; }
        public string OnHold { get; set; }
        public int AppliesToDocType { get; set; }
        public string AppliesToDocNo { get; set; }
        public string BalAccountNo { get; set; }
        public byte Ship { get; set; }
        public byte Invoice { get; set; }
        public byte PrintPostedDocuments { get; set; }
        public string ShippingNo { get; set; }
        public string PostingNo { get; set; }
        public string LastShippingNo { get; set; }
        public string LastPostingNo { get; set; }
        public string PrepaymentNo { get; set; }
        public string LastPrepaymentNo { get; set; }
        public string PrepmtCrMemoNo { get; set; }
        public string LastPrepmtCrMemoNo { get; set; }
        public string VatRegistrationNo { get; set; }
        public byte CombineShipments { get; set; }
        public string ReasonCode { get; set; }
        public string GenBusPostingGroup { get; set; }
        public byte Eu3PartyTrade { get; set; }
        public string TransactionType { get; set; }
        public string TransportMethod { get; set; }
        public string VatCountryRegionCode { get; set; }
        public string SellToCustomerName { get; set; }
        public string SellToCustomerName2 { get; set; }
        public string SellToAddress { get; set; }
        public string SellToAddress2 { get; set; }
        public string SellToCity { get; set; }
        public string SellToContact { get; set; }
        public string BillToPostCode { get; set; }
        public string BillToCounty { get; set; }
        public string BillToCountryRegionCode { get; set; }
        public string SellToPostCode { get; set; }
        public string SellToCounty { get; set; }
        public string SellToCountryRegionCode { get; set; }
        public string ShipToPostCode { get; set; }
        public string ShipToCounty { get; set; }
        public string ShipToCountryRegionCode { get; set; }
        public int BalAccountType { get; set; }
        public string ExitPoint { get; set; }
        public byte Correction { get; set; }
        public DateTime DocumentDate { get; set; }
        public string ExternalDocumentNo { get; set; }
        public string Area { get; set; }
        public string TransactionSpecification { get; set; }
        public string PaymentMethodCode { get; set; }
        public string ShippingAgentCode { get; set; }
        public string PackageTrackingNo { get; set; }
        public string NoSeries { get; set; }
        public string PostingNoSeries { get; set; }
        public string ShippingNoSeries { get; set; }
        public string TaxAreaCode { get; set; }
        public byte TaxLiable { get; set; }
        public string VatBusPostingGroup { get; set; }
        public int Reserve { get; set; }
        public string AppliesToId { get; set; }
        public decimal VatBaseDiscount { get; set; }
        public int Status { get; set; }
        public int InvoiceDiscountCalculation { get; set; }
        public decimal InvoiceDiscountValue { get; set; }
        public byte SendIcDocument { get; set; }
        public int IcStatus { get; set; }
        public string SellToIcPartnerCode { get; set; }
        public string BillToIcPartnerCode { get; set; }
        public int IcDirection { get; set; }
        public decimal Prepayment { get; set; }
        public string PrepaymentNoSeries { get; set; }
        public byte CompressPrepayment { get; set; }
        public DateTime PrepaymentDueDate { get; set; }
        public string PrepmtCrMemoNoSeries { get; set; }
        public string PrepmtPostingDescription { get; set; }
        public DateTime PrepmtPmtDiscountDate { get; set; }
        public string PrepmtPaymentTermsCode { get; set; }
        public decimal PrepmtPaymentDiscount { get; set; }
        public string QuoteNo { get; set; }
        public DateTime QuoteValidUntilDate { get; set; }
        public DateTime QuoteSentToCustomer { get; set; }
        public byte QuoteAccepted { get; set; }
        public DateTime QuoteAcceptedDate { get; set; }
        public int JobQueueStatus { get; set; }
        public Guid JobQueueEntryId { get; set; }
        public string CompanyBankAccountCode { get; set; }
        public int IncomingDocumentEntryNo { get; set; }
        public byte IsTest { get; set; }
        public string SellToPhoneNo { get; set; }
        public string SellToEMail { get; set; }
        public int PaymentInstructionsId { get; set; }
        public string JournalTemplName { get; set; }
        public byte[] WorkDescription { get; set; }
        public int DimensionSetId { get; set; }
        public int PaymentServiceSetId { get; set; }
        public string DirectDebitMandateId { get; set; }
        public int DocNoOccurrence { get; set; }
        public string CampaignNo { get; set; }
        public string SellToCustomerTemplateCode { get; set; }
        public string SellToContactNo { get; set; }
        public string BillToContactNo { get; set; }
        public string BillToCustomerTemplateCode { get; set; }
        public string OpportunityNo { get; set; }
        public string SellToCustomerTemplCode { get; set; }
        public string BillToCustomerTemplCode { get; set; }
        public string ResponsibilityCenter { get; set; }
        public int ShippingAdvice { get; set; }
        public int PostingFromWhseRef { get; set; }
        public DateTime RequestedDeliveryDate { get; set; }
        public DateTime PromisedDeliveryDate { get; set; }
        public string ShippingTime { get; set; }
        public string OutboundWhseHandlingTime { get; set; }
        public string ShippingAgentServiceCode { get; set; }
        public byte Receive { get; set; }
        public string ReturnReceiptNo { get; set; }
        public string ReturnReceiptNoSeries { get; set; }
        public string LastReturnReceiptNo { get; set; }
        public int PriceCalculationMethod { get; set; }
        public byte AllowLineDisc { get; set; }
        public byte GetShipmentUsed { get; set; }
        public Guid Id { get; set; }
        public string AssignedUserId { get; set; }
        public byte Adjustment { get; set; }
        public byte BasAdjustment { get; set; }
        public string AdjustmentAppliesTo { get; set; }
        public string WhtBusinessPostingGroup { get; set; }
        public decimal WhtAmount { get; set; }
        public int TaxDocumentType { get; set; }
        public byte PrintedTaxDocument { get; set; }
        public byte PostedTaxDocument { get; set; }
        public byte TaxDocumentMarked { get; set; }
        public Guid SystemId { get; set; }
        public DateTime SystemCreatedAt { get; set; }
        public Guid SystemCreatedBy { get; set; }
        public DateTime SystemModifiedAt { get; set; }
        public Guid SystemModifiedBy { get; set; }
    }
}
